# Generated by Django 4.0.4 on 2022-05-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='apple', max_length=128),
            preserve_default=False,
        ),
    ]
